feat: update workflows

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -5,19 +5,42 @@ name: Node.js Package
 
 on:
   push:
-    tags:
-      - '*'
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
           node-version: 16
-      - run: npm ci
-      - run: npm test
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Run tests
+        run: npm test
+
+      - name: Check NPM version
+        id: check-version
+        run: |
+          CURRENT_VERSION=$(node -p "require('./package.json').version")
+          CURRENT_NAME=$(node -p "require('./package.json').name")
+          LATEST_VERSION=$(npm show $CURRENT_NAME version)
+          echo "Current version: $CURRENT_VERSION"
+          echo "Latest version: $LATEST_VERSION"
+          echo "::set-output name=needs-publish::$(test $CURRENT_VERSION != $LATEST_VERSION && echo true || echo false)"
+      
+      - name: Stop workflow if no update
+        if: steps.check-version.outputs.needs-publish == 'false'
+        run: |
+          echo "No update required"
+          exit 0
 
   publish-npm:
     needs: build
@@ -30,5 +53,9 @@ jobs:
           registry-url: https://registry.npmjs.org/
       - run: npm ci
       - run: npm publish
+      - run: |
+          NEW_VERSION=$(node -p "require('./package.json').version")
+          git tag $NEW_VERSION
+          git push origin $NEW_VERSION
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
